### ISSUE TITLE
Does this package support specifying a path to config?

### ISSUE THREAD

**Issue by viT-1** [sleep-written/ts-path-mapping#1]
Am I restricted to use only tsconfig.json in the root of my project?
For example [nested tsconfig project](https://github.com/viT-1/systemjs-ts-es6).

**Comment by sleep-written** [comment]
For now, the library only reads the `tsconfig.json` root file, but in a major new version I have plans to add the ability to read nested files.

**Comment by viT-1** [comment]
@sleep-written Do you have plans to add cli key for different name of tsconfig file?

**Comment by sleep-written** [comment]
If you refer to create a CLI for execute a project providing a custom `tsconfig` (with the custom paths), this sounds an interesting feature that I would can add to the next version.

I will considerate an integration with `ts-node` too.
